# --- Tile proxies (so CSP is easy and no CORS issues) ---

[[redirects]]
  from = "/tiles/osm/*"
  to   = "https://a.tile.openstreetmap.org/:splat"
  status = 200
  force  = true

[[redirects]]
  from = "/tiles/orm/*"
  to   = "https://a.tile.openrailwaymap.org/standard/:splat"
  status = 200
  force  = true