[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  path = "/dashboard.html"
  function = "protect"

[[edge_functions]]
  path = "/admin.html"
  function = "protect"

[[edge_functions]]
  path = "/flight.html"
  function = "protect"

[[edge_functions]]
  path = "/database.html"
  function = "protect"

[[edge_functions]]
  path = "/dashboard"
  function = "protect"

[[edge_functions]]
  path = "/admin"
  function = "protect"

[[edge_functions]]
  path = "/flight"
  function = "protect"

[[edge_functions]]
  path = "/database"
  function = "protect"
